### ISSUE TITLE
rif-storage-js Not Found into npm 

### ISSUE THREAD

**Issue by jegox** [rsksmart/rif-storage-js#15]
I try to install rif-storage but i get not found
`https://registry.npmjs.org/rif-storage - Not found`

**Comment by AuHau** [comment]
Hey there,
sorry, the library is still not released. So you can not install it using `npm i rif-storage`. If you want to try it out before release (it should be released in upcoming days) you should be able to install it using `npm i rsksmart/rif-storage-js`, yet be warned that even though we try to keep master stable, it might fail at some point. So good for playing around, not good for anything serious ;-)

**Comment by AuHau** [comment]
The package was released, hence closing this.
https://www.npmjs.com/package/@rsksmart/rif-storage

**Comment by jegox** [comment]
thanks you!
